# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Y2NkYzJlMGE1YmZmYmZkYzYwOTEwZjMxMDcwZjY2ODBlNjY4NzVkMGIxYWY4ZGY0Njk2NDI3Y2ZjMmFmODE4NGQxN2YxYjk1ZDNmYjc4M2UyYTMzMmRjY2EwOGUzNzY5MzRkYTViNjg4MzQ1NTIyNTg2NWM3ZWFiYzRjNzI3YmM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
